service: lang-count-service

# Add the serverless-webpack plugin
plugins:
   - serverless-webpack

provider:
   name: aws
   stage: ${opt:stage, self:custom.defaultStage}
   runtime: nodejs14.x
   lambdaHashingVersion: 20201221

functions:
   langCount:
      handler: handler.langCount
      memorySize: 256
      events:
         - http:
             method: get
             path: langCount

custom:
   defaultStage: dev
