service:
   name: lang-count-service

# Add the serverless-webpack plugin
plugins:
   - serverless-webpack

provider:
   name: aws
   runtime: nodejs8.10

functions:
   langCount:
      handler: handler.langCount
      events:
         - http:
             method: get
             path: langCount
