service:
   name: lang-count-service

# Add the serverless-webpack plugin
plugins:
   - serverless-webpack

provider:
   name: aws
   runtime: nodejs8.10

functions:
   lang-count:
      handler: handler.lang-count
      events:
         - http:
             method: get
             path: lang-count
